### ISSUE TITLE
Generate multiple compatibility MC releases

### ISSUE THREAD

**Issue by cyrilchapon** [Glitchfiend/Bullseye#11]
Hey,

Thanks for your awesome mod(s..).

Would it be possible to make some 1.8.9 et 1.9.X versions ?

Some mod do, so I assume it's achievable, but I don't know the cost.

Thanks =)

**Comment by Forstride** [comment]
"but I don't know the cost."

The cost is rewriting the entire mod.  Also, we *do* have a 1.9.4 version, which is forward compatible with 1.10.
