### ISSUE TITLE
Compactability Between Tinkers Construct and Bullseye

### ISSUE THREAD

**Issue by Quizer9O8** [Glitchfiend/Bullseye#13]
Can you fire of BE arrows on a TC bow?
If not it would be nice if it's made possible

**Comment by Forstride** [comment]
Did you even test it...?  Please don't open issues unless it's actually an issue.

Regardless, if it didn't work, that's something they'd have to fix.  Our arrows work automatically with vanilla bows, and should work with TC bows assuming they know what they're doing.

**Comment by Quizer9O8** [comment]
Oké, where do i have to put my future suggestions next time then, and yes it isn't possible to shoot BE arrrows with a TC bow.

**Comment by Forstride** [comment]
"Regardless, if it didn't work, that's something they'd have to fix."

Ask them?
