### ISSUE TITLE
egg arrow recipe doesn't make sense.

### ISSUE THREAD

**Issue by FELITH** [Glitchfiend/Bullseye#14]
use 1 egg and get 4 egg arrows. (sorry for my bad english.)

**Comment by Adubbz** [comment]
I don't really think this logic quite works. For example, a single flint, a single stick and a single feather produces four arrows. 7 sticks in a ladder shape produces 3 ladders. A single arrow surrounded by four glowstone produces two spectral arrows. Etc. etc.

'Real life logic' doesn't apply in games, it's about what's fun and intuitive for the player. Why bother making egg arrows at all if it's unnecessarily costly to do so? In games, it's always important to consider reward vs cost above what's most realistic.

**Comment by FELITH** [comment]
oh that what you explained. It's make sense to me now. xD thx
